[package]
name = "lightbridge-repo-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "lightbridge-repo-auth"
path = "src/main.rs"

[dependencies]
lightbridge-repo-auth-core.workspace = true

serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
axum.workspace = true
axum-server.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
dotenvy.workspace = true
anyhow.workspace = true
rustls.workspace = true
mimalloc.workspace = true
