{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "lra.name" . }}
  labels:
    {{- include "lra.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.storeRef }}
  target:
    name: {{ include "lra.name" . }}
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.props.databaseUrl }}
    - secretKey: webhook-secret
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.props.webhookSecret }}
    - secretKey: internal-token
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.props.internalToken }}
    - secretKey: private-key.pem
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.props.privateKeyPem }}
{{- end }}
