apiVersion: v1
kind: Service
metadata:
  name: {{ include "lra.name" . }}
  labels:
    {{- include "lra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "lra.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
